# .goreleaser.yaml
version: 2

# Désactive la construction
builds:
  - skip: true

# Configuration Docker uniquement
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Tag }}"
    dockerfile: Dockerfile
    # IMPORTANT: Spécifiez les fichiers à inclure dans le contexte de build
    extra_files:
      - main.py
      - pyproject.toml
      - uv.lock
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

# Désactive les checksums
checksum:
  disable: true

# Désactive le changelog
changelog:
  disable: true

# Configuration release
release:
  draft: true
  replace_existing_draft: true