# .goreleaser.yaml
version: 2

# Disable binary builds, only build Docker image
builds:
  - skip: true

# Configuration Docker v2 (multi-arch)
dockers_v2:
  - id: "apache-superset"
    images:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    # Add Tags to the image, including "latest" and the version tag
    tags:
      - "latest"
      - "{{ .Tag }}"
    # Path to the Dockerfile (relative to the repository root)
    dockerfile: docker/apache-superset/Dockerfile
    # Additional files to include in the Docker build context (relative to the repository root)
    extra_files:
      - docker/apache-superset/config/superset_config.py
      - docker/apache-superset/config/example.env
    # Labels OCI pour la metadata
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    # Plateforms targets (ex: linux/amd64, linux/arm64)
    platforms:
      - linux/amd64
    # Disable SBOM release artifacts
    sbom: false
