# .github/workflows/announce-release.yml
name: Announce Release

on:
  release:
    types: [published]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create announcement
        uses: ./.github/actions/releases-announcement
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          category: "announcements" # ou "general", "show-and-tell"
